name: Deploy EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets. SSH_HOST }}
        username: ${{ secrets. SSH_USER }}
        port: ${{ secrets. SSH_PORT }}
        key: ${{ secrets. SSH_KEY }}
        source: "., !node_modules"
        target: "~/app/integrations"
    
    - name: Update HTML
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /
          cat /usr/share/nginx/html
         
